<a href="https://colab.research.google.com/github/KIM-KWAN-IL/Test/blob/main/DL_Lab3_Example_Code_logistic_regresstion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Example 1

In [ ]:
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
import torch.nn.functional as F

x_data = [[80,220],[75,167],[86,210],[110,330],[95,280],[67,190],[79,210],[98,250]]
y_data = [[1],[0],[1],[1],[1],[0],[0],[1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print('x_train size =', x_train.shape)
print('y_train size =', y_train.shape)

W = torch.zeros((2,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

print('------------------------------')
print('< Before Train >')
print('W size =', W)
print('b size =', b)

optimizer = optim.SGD([W,b], lr= 0.00001)

for e in range(1000):
  optimizer.zero_grad()
  #hypothesis = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))
  hypothesis = torch.sigmoid(x_train.matmul(W)+b)
  #loss = -(y_train * torch.log(hypothesis) + (1 - y_train) * torch.log(1 - hypothesis))
  #cost = loss.mean()
  cost = F.binary_cross_entropy(hypothesis, y_train) # Softmax included
  cost.backward()
  optimizer.step()

  if e % 100 == 0:
    print('epoch:%d cost:%f'%(e, cost))


print('------------------------------')
print('< After Train >')
print('W = ', W)
print('b =', b)

prediction = 1 / (1 + torch.exp(-(x_train.matmul(W) + b)))
# hypothsis 는 0과 1사이의 실수값이므로, 그 값이 0.5 보다 크면 1, 작으면 0 ==> binary classification
correct_prediction = prediction.float() == y_train


print('------------------------------')
print('< Evaluation >')
print(prediction)
print(correct_prediction)

x_train size = torch.Size([8, 2])
y_train size = torch.Size([8, 1])
------------------------------
< Before Train >
W size = tensor([[0.],
        [0.]], requires_grad=True)
b size = tensor([0.], requires_grad=True)
epoch:0 cost:0.693147
epoch:100 cost:0.618535
epoch:200 cost:0.617527
epoch:300 cost:0.616542
epoch:400 cost:0.615580
epoch:500 cost:0.614641
epoch:600 cost:0.613723
epoch:700 cost:0.612827
epoch:800 cost:0.611952
epoch:900 cost:0.611097
------------------------------
< After Train >
W =  tensor([[-0.0079],
        [ 0.0063]], requires_grad=True)
b = tensor([-0.0006], requires_grad=True)
------------------------------
< Evaluation >
tensor([[0.6800],
        [0.6127],
        [0.6554],
        [0.7703],
        [0.7337],
        [0.6609],
        [0.6678],
        [0.6900]], grad_fn=<MulBackward0>)
tensor([[False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False],
        [False]])


# Example 1 with Higher Implementation

In [ ]:
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
import torch.nn.functional as F

x_data = [[80,220],[75,167],[86,210],[110,330],[95,280],[67,190],[79,210],[98,250]]
y_data = [[1],[0],[1],[1],[1],[0],[0],[1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print('x_train size =', x_train.shape)
print('y_train size =', y_train.shape)

class BinaryClassifier(nn.Module):
  def __init__(self):
    super(BinaryClassifier, self).__init__()
    self.linear = nn.Linear(2,1) # 입력차원 : 2, 출력차원: 1
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    return self.sigmoid(self.linear(x))

model = BinaryClassifier() # 모델 초기화

optimizer = optim.SGD(model.parameters(), lr= 1e-6) # optimizer 설정

for e in range(1000):
  hypothesis = model(x_train)
  cost = F.binary_cross_entropy(hypothesis, y_train) # Softmax included
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if e % 100 == 0:
    print('epoch:%d cost:%f'%(e, cost))

prediction = hypothesis >= torch.FloatTensor([0.5])
# hypothsis 는 0과 1사이의 실수값이므로, 그 값이 0.5 보다 크면 1, 작으면 0 ==> binary classification
correct_prediction = prediction.float() == y_train

print('------------------------------')
print('< Evaluation >')
print(prediction)


x_train size = torch.Size([8, 2])
y_train size = torch.Size([8, 1])
epoch:0 cost:3.497896
epoch:100 cost:1.171866
epoch:200 cost:0.711561
epoch:300 cost:0.689296
epoch:400 cost:0.687891
epoch:500 cost:0.687617
epoch:600 cost:0.687413
epoch:700 cost:0.687214
epoch:800 cost:0.687016
epoch:900 cost:0.686818
------------------------------
< Evaluation >
tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True]])


# Binary Classification Example

In [ ]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]] # False False False True True  True

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=1) # SGD 사용

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    # Cost 계산
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = F.binary_cross_entropy(hypothesis, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번 마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d} / {} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

hypothesis = torch.sigmoid(x_train.matmul(W) + b)
prediction = hypothesis >= torch.FloatTensor([0.5]) #  0.5를 넘으면 True, 넘지 않으면 False
correct_prediction = prediction.float() == y_train

print(hypothesis)
print(prediction)
print(correct_prediction)


Epoch    0 / 1000 Cost: 0.693147
Epoch  100 / 1000 Cost: 0.134722
Epoch  200 / 1000 Cost: 0.080643
Epoch  300 / 1000 Cost: 0.057900
Epoch  400 / 1000 Cost: 0.045300
Epoch  500 / 1000 Cost: 0.037261
Epoch  600 / 1000 Cost: 0.031672
Epoch  700 / 1000 Cost: 0.027556
Epoch  800 / 1000 Cost: 0.024394
Epoch  900 / 1000 Cost: 0.021888
Epoch 1000 / 1000 Cost: 0.019852
tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)
tensor([[False],
        [False],
        [False],
        [ True],
        [ True],
        [ True]])
tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True]])


# Example 2

In [ ]:
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
import torch.nn.functional as F

x_data = [[80, 220, 6300], # 2 - cheetah
          [75, 167, 4500], # 3 - jaguar
          [86, 210, 7500], # 1 - leopard
          [110, 330, 9000], # 0 - tiger
          [95, 280, 8700], # 0 - tiger
          [67, 190, 6800], # 3 - jaguar
          [79, 210, 5000], # 2 - cheetah
          [98, 250, 7200]] # 1 - leopard

y_data = [2, 3, 1, 0, 0, 3, 2, 1]

nb_class = 4 # tiger, leopard, cheetah, jaguar
classes = {0: "Tiger", 1: "Leopard", 2: "Cheetah", 3: "Jaguar"}

x_train = torch.FloatTensor(x_data)
y_train = torch.LongTensor(y_data)

print('x_train size =', x_train.shape)
print('y_train size =', y_train.shape)

W = torch.zeros((3, nb_class), requires_grad = True)
b = torch.zeros(1, requires_grad = True) # nb_class --> need to used multi perceptron

print('W size =', W.shape)
print('b size =', b.shape)

optimizer = optim.SGD([W,b], lr = 0.00001)

for e in range(10000):
  optimizer.zero_grad()
  hypothesis = torch.sigmoid(x_train.matmul(W)+b) # Activation Function
  cost = F.cross_entropy(hypothesis, y_train) # Softmax included
  cost.backward()
  optimizer.step()

  if e % 1000 == 0:
    print('epoch:%d cost:%f'%(e, cost))

print('< After Train >')
print('W = ', W)
print('b =', b)

prediction = torch.sigmoid(x_train.matmul(W) + b)

print('---------')
print('< Evaluation >')
print(prediction)

x_train size = torch.Size([8, 3])
y_train size = torch.Size([8])
W size = torch.Size([3, 4])
b size = torch.Size([1])
epoch:0 cost:1.386294
epoch:1000 cost:1.380785
epoch:2000 cost:1.379236
epoch:3000 cost:1.377279
epoch:4000 cost:1.375425
epoch:5000 cost:1.380006
epoch:6000 cost:1.372731
epoch:7000 cost:1.380072
epoch:8000 cost:1.382767
epoch:9000 cost:1.380724
< After Train >
W =  tensor([[-1.5915e-04, -5.0109e-03,  4.4209e-05,  4.6111e-05],
        [ 4.4413e-05, -3.4068e-02,  1.4390e-04,  7.5486e-05],
        [ 2.1288e-03,  2.0382e-03,  2.1328e-03,  2.6649e-03]],
       requires_grad=True)
b = tensor([-0.0002], requires_grad=True)
---------
< Evaluation >
tensor([[1.0000, 0.9929, 1.0000, 1.0000],
        [0.9999, 0.9572, 0.9999, 1.0000],
        [1.0000, 0.9995, 1.0000, 1.0000],
        [1.0000, 0.9986, 1.0000, 1.0000],
        [1.0000, 0.9996, 1.0000, 1.0000],
        [1.0000, 0.9991, 1.0000, 1.0000],
        [1.0000, 0.9334, 1.0000, 1.0000],
        [1.0000, 0.9966, 1.0000, 1.0000

# Possible Solution 1

In [ ]:
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init
import torch.nn.functional as F

class MultiClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(8, 4)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        return self.sigmoid(self.linear(x))

model = BinaryClassifier()

x_data = [[80, 220, 6300], # 2 - cheetah
          [75, 167, 4500], # 3 - jaguar
          [86, 210, 7500], # 1 - leopard
          [110, 330, 9000], # 0 - tiger
          [95, 280, 8700], # 0 - tiger
          [67, 190, 6800], # 3 - jaguar
          [79, 210, 5000], # 2 - cheetah
          [98, 250, 7200]] # 1 - leopard

y_data = [2, 3, 1, 0, 0, 3, 2, 1]
y_one_hot = [[0, 0, 1, 0],
             [0, 0, 0, 1],
             [0, 1, 0, 0],
             [1, 0, 0, 0],
             [1, 0, 0, 0],
             [0, 0, 1, 0],
             [0, 0, 1, 0],
             [0, 1, 0, 0]
             ]

nb_class = 4 # tiger, leopard, cheetah, jaguar
classes = {0: "Tiger", 1: "Leopard", 2: "Cheetah", 3: "Jaguar"}

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_one_hot)

print('x_train size =', x_train.shape)
print('y_train size =', y_train.shape)

W = torch.zeros((3, nb_class), requires_grad = True)
b = torch.zeros(nb_class, requires_grad = True) # nb_class --> need to used multi perceptron

print('W size =', W.shape)
print('b size =', b.shape)

optimizer = optim.SGD([W,b], lr = 1e-6)

for e in range(10000):
  optimizer.zero_grad()
  hypothesis = torch.sigmoid(x_train.matmul(W)+b) # Activation Function
  cost = F.cross_entropy(hypothesis, y_train) # Softmax included
  cost.backward()
  optimizer.step()

  if e % 1000 == 0:
    print('epoch:%d cost:%f'%(e, cost))

print('< After Train >')
print('W = ', W)
print('b =', b)

prediction = torch.sigmoid(x_train.matmul(W) + b)

print('---------')
print('< Evaluation >')
print(prediction)

x_train size = torch.Size([8, 3])
y_train size = torch.Size([8, 4])
W size = torch.Size([3, 4])
b size = torch.Size([4])
epoch:0 cost:1.386294
epoch:1000 cost:1.294630
epoch:2000 cost:1.293651
epoch:3000 cost:1.292665
epoch:4000 cost:1.291668
epoch:5000 cost:1.290663
epoch:6000 cost:1.289652
epoch:7000 cost:1.288638
epoch:8000 cost:1.287622
epoch:9000 cost:1.286609
< After Train >
W =  tensor([[-3.5448e-03, -3.0706e-04,  1.8038e-05,  3.2536e-03],
        [ 1.6219e-03, -8.2642e-03,  7.1303e-05,  2.2952e-03],
        [ 1.5829e-04,  4.0599e-04,  1.6471e-03, -4.1040e-04]],
       requires_grad=True)
b = tensor([-1.1345e-04, -3.9175e-05,  2.5380e-07,  5.9185e-05],
       requires_grad=True)
---------
< Evaluation >
tensor([[0.7447, 0.6715, 1.0000, 0.1394],
        [0.6720, 0.6044, 0.9994, 0.2280],
        [0.7726, 0.7830, 1.0000, 0.0898],
        [0.8278, 0.7095, 1.0000, 0.0706],
        [0.8167, 0.7665, 1.0000, 0.0679],
        [0.7590, 0.7631, 1.0000, 0.1056],
        [0.7010, 0.5671, 0.9